CREATE DATABASE DENTAL;


CREATE TABLE USUARIOS(
    idUsuario INT NOT NULL PRIMARY KEY,
    idRole INT(2) NOT NULL, 
    nombre VARCHAR(30) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    telefono INT(10) NOT NULL,
    correo VARCHAR(30) NOT NULL,
    FOREIGN KEY (idRole) REFERENCES ROLES(idRole)
);

CREATE TABLE ROLES(
    idRole INT(3) NOT NULL PRIMARY KEY, 
    tipoRole VARCHAR(30) NOT NULL
);

CREATE TABLE CITAS(
    idCita INT(4) NOT NULL PRIMARY KEY,
    idPaciente INT NOT NULL,
    idDentista INT NOT NULL,
    fecha DATE NOT NULL,
    horario INT NOT NULL,
    FOREIGN KEY (idPaciente) REFERENCES USUARIOS(idUsuario),
    FOREIGN KEY (idDentista) REFERENCES USUARIOS(idUsuario)
);
